### ISSUE TITLE
Adapt hadley`s R package checklist to KWB needs (packages, workflows, and so on)?

### ISSUE THREAD

**Issue by mrustl** [KWB-R/fakin.doc#18]
* [ ] `devtools::check_win_devel()`
* [ ] `rhub::check_for_cran()`
* [ ] `revdepcheck::revdep_check(num_workers = 4)`
* [ ] [Polish NEWS](http://style.tidyverse.org/news.html#before-release)
* [ ] If new failures, update `email.yml` then `revdepcheck::revdep_email_maintainers()`
* [ ] Bump version (in DESCRIPTION and NEWS)
* [ ] `devtools::check_win_devel()` (again!)
* [ ] `devtools::submit_cran()`
* [ ] `pkgdown::build_site()`
* [ ] Approve email
* [ ] Tag release
* [ ] Bump dev version
* [ ] Write blog post
* [ ] Tweet

Template from <https://github.com/r-lib/usethis/issues/338>

Too advanced for us as focuss is on CRAN release (as for ggplot2 3.0 https://github.com/tidyverse/ggplot2/issues/2568) but we can use it as a starting point

**Comment by mrustl** [comment]
**How to create a TO DO list in rmarkdown:**

> According to pandoc tricks, you may first download the [task-list.lua](https://github.com/pandoc/lua-filters/blob/master/task-list/task-list.lua) file and save it in $DATADIR/pandoc/filters/, so it will be visible to pandoc system-wide, then run pandoc --lua-filter=task-list.lua -o filename.html filename.md 

_Source: https://stackoverflow.com/questions/28628903/to-do-list-in-rmarkdown_
