### ISSUE TITLE
Roadmap: case study "geosalz"

### ISSUE THREAD

**Issue by mrustl** [KWB-R/fakin.doc#25]
* [ ] `Improved folder structure analysis and documentation using function kwb.fakin::plot_path_tree()` **(to be added in kwb.geosalz documentation**
* [x] ` Workflow documentation` **for process check https://kwb-r.github.io/kwb.geosalz/dev/articles/workfow.html**
* [ ] ` Add  short documentation in fakin.doc` **for progress check https://kwb-r.github.io/fakin.doc/case-studies.html#geogenic-salination**
