### ISSUE TITLE
Roadmap: case study "LCA"

### ISSUE THREAD

**Issue by mrustl** [KWB-R/fakin.doc#26]
* [ ] `Improved folder structure analysis and documentation using function kwb.fakin::plot_path_tree()` **(to be added in kwb.geosalz documentation**
* [] ` Add feature in R pakcage kwb.umberto` **for process check https://github.com/KWB-R/kwb.umberto/issues/2**
* [] ` Workflow documentation` 
* [ ] ` Add  short documentation in fakin.doc` **for progress check https://kwb-r.github.io/fakin.doc/case-studies.html#lca-modelling**
